const data = {
  products: [
    {
      id: '001',
      name: 'Gold-Floral-ring',
      slug: 'gold-floral-ring',
      category: 'Rings',
      image: '/images/ring1.jpg',
      price: '3,647.00',
      qualit: '916',
      rating: '4.5',
      numReviews: '10',
      description: 'Great design ring',
    },
    {
      id: '002',
      name: 'Gold-Heart-ring',
      slug: 'gold-heart-ring',
      category: 'Rings',
      image: '/images/ring2.jpg',
      price: '2,643.00',
      qualit: '916',
      rating: '3.0',
      numReviews: '10',
      description: 'Great design ring',
    },
    {
      id: '003',
      name: 'Gold-Daisy-chain',
      slug: 'gold-daisy-chain',
      category: 'Chains',
      image: '/images/ring3.jpg',
      price: '1,999.00',
      qualit: '916',
      rating: '4.3',
      numReviews: '10',
      description: 'Great design chain',
    },
    {
      id: '004',
      name: 'Gold-Ohm-chain',
      slug: 'gold-ohm-chain',
      category: 'Chains',
      image: '/images/ring4.jpg',
      price: '2,999.00',
      qualit: '916',
      rating: '3.7',
      numReviews: '8',
      description: 'Great design chain',
    },
  ],
};
export default data;
